language: node_js
node_js:
- '7'
- '6'
- '5'
- '4'
install:
- NODE_ENV=development npm install
before_script:
- npm run lint
script:
- npm run test:coverage
after_script:
- npm run test:report
deploy:
  provider: npm
  email: npm@devlato.com
  api_key:
    secure: KFpexf5WQ4xjmBzmmjnTagQBT2JzM+0W9XPOaufxubJJAM4ukcBvmmtLfvwQWgGl75OB5h8olHPifm9dDEeTGqASG13mM+pPjYhFwLo6LEbVSU/rXZaJorxsJrg8gQdi9IJmLVtXP7bnvKvG6EQuNyqPzPSObHG3nH/+Ys14Uq1WJwoClpYmBCv9rNDqP3a89Qb3QGnGExzuEGlmpgnW0A6mDIQzxHiuJgn9HjKPOHrAOdWwQpSQuD5qTLSuV07asnsTRQgNrf6+ds19z26pOyvn8nSBzePmWKctBai2LvdV4aKj/hePY+Idkq8z1I1R1w3fczsf+7CuwhjNtzVXwqVo8SoGreGHDTmGCzKEq9VXyFFjPqWZ8hPKcXAwzfe/ipkfD5ANZzciaLSAf/J1VubPxi4wZ+oX0mS5uKKBEaRKdsvh05748MW2NEiy+2PYIV//DgmufSzky8OW0gTVQ/pUpJwQO2vbZWXtorKG/iBq45Q1zM4ar6Znbxg2QioojFCBO6LBqImL5jvnUDY+djHrXU4S8T7BYZ+RbdMsxaYvTqGX4Xdul6zLchY7esEQ95wyLI3StJoE8coeqdW2zPRmB9z64VD1eIpwwEj4DqqYL4YCO/HnPA78M3LYgyHXnjo9po46871yhX5ego1IoLwSkDiEdTqOVXKfIudHBck=
  on:
    tags: true
    repo: devlato/react-hotkeys
